name: restaurants-api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # 2️⃣ Setup .NET SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 8.0.x

      # 3️⃣ Clean previous builds
      - name: Clean
        run: dotnet clean Restaurants.Api/Restaurants.Api.sln

      # 4️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Restaurants.Api/Restaurants.Api.sln

      # 5️⃣ Build without treating warnings as errors (temporary while fixing code)
      - name: Build
        run: dotnet build Restaurants.Api/Restaurants.Api.sln --configuration Release /p:TreatWarningsAsErrors=false

      # 6️⃣ Run tests with better error handling and logging
      - name: Test
        run: |
          echo "Running tests for the solution..."
          dotnet test Restaurants.Api/Restaurants.Api.sln --no-build --verbosity normal --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage" --results-directory ./coverage
        continue-on-error: false

      # 7️⃣ Display test results summary
      - name: Test Results Summary
        if: always()
        run: |
          echo "Test execution completed. Checking for test results..."
          if [ -d "./coverage" ]; then
            echo "Test coverage reports generated successfully."
          else
            echo "No test coverage reports found."
          fi
