name: restaurants-api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # 2️⃣ Setup .NET SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 8.0.x

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Restaurants.Api/Restaurants.Api.sln

      # 4️⃣ Build without treating warnings as errors (temporary while fixing code)
      - name: Build
        run: dotnet build Restaurants.Api/Restaurants.Api.sln --configuration Release /p:TreatWarningsAsErrors=false

      # 5️⃣ Run all tests in the solution
      - name: Test
        run: dotnet test Restaurants.Api/Restaurants.Api.sln --no-build --verbosity normal
